### ISSUE TITLE
Zu den Statistiken

### ISSUE THREAD

**Issue by gtbu** [davidstutz/cmsimple-bbclone#3]
What one could improve is the new bbclone version 0.64 and the possibility to adjust the bbclone-parameters within the konfiguration of the plugin

Another point is that  every visitor can see my statistics by just adding bbclone/
something like 'if adm' is missing!

Within bbclone a total statistich of all sites would be great.

**Comment by davidstutz** [comment]
Yes, updating BBClone is a good idea.

Well, as BBClone is completely external, it cannot easily be checked whether somebody is logged in in the CMSimple installation. And as far as I know, BBClone does not offer that feature, does it? So the easiest solution here is to use a `.htaccess` file. But this is highly specific to the CMSimple installation (provider, directory, other installations etc.). So I will not include this in the plugin but consider to mention it in the documentation.

And the last item would also be a BBClone issue I guess.

**Comment by davidstutz** [comment]
Addressed the first and second point in the last commit.
