### ISSUE TITLE
XH 17 menu

### ISSUE THREAD

**Issue by gtbu** [davidstutz/cmsimple-bbclone#4]
The menu does not appear in XH 1.7

**Comment by davidstutz** [comment]
The [demo](http://davidstutz.de/cmsimplexhdemo/?Start) runs CMsimpel XH 1.7.2 and the BBClone item appears in the menu as expected.

![bbclone](https://user-images.githubusercontent.com/1203091/36326850-dbbf14a6-135c-11e8-88cc-1d0a483bd98e.png)

Can you give details on what exactly you mean and which version/plugisn you are running?
