### ISSUE TITLE
..does not run properly inside the plugin class

### ISSUE THREAD

**Issue by manu37** [davidstutz/cmsimple-bbclone#6]
bbclone doesn't run properliy inside the plugin class. You can test it on your Demo page, the page views are not tracked, only the bbclone page views. bbclone is ment to run on top level, not to be included inside a class. When running inside a class, the bbclone functions don't have a proper scope to the necessary global bbclone constants and config values. You could set them global before the bbclone include, but IMHO this is not the best practise. I made the best experiences to use the userprelude.php to prior include the cms(imple).php followed by the bbclone sequence.
regards
manu

**Comment by davidstutz** [comment]
I can't really follow you. If I try it on the demo page, accessing various different pages, the counts are correctly increased. In fact, the counts for the BBClone pages are the lowest because I rarely check them (< 10 views), while the counts for the example pages of other plugins are significantly higher (> 1500).

**Comment by manu37** [comment]
I just stepped through the most of your cmsimplexhdemo pages. BBClone detailed stats shows only the BBClone Hits: http://davidstutz.de/cmsimplexhdemo/bbclone/show_views.php?id=4088&lng=de. The counters of the main statistik seem ok.

**Comment by davidstutz** [comment]
I see. Also, the detailed stats seem to be reset every now and then - meaning even the BBClone hits are reset after some minutes (or even seconds). 

So far, I actually cannot find the problem. The inserted activation code for bbclone should be generated correctly on all pages according to the documentation. Also, based on the documentation, there does not seem to be a distinction between the main stats and the detailed stats section ...

**Comment by manu37** [comment]
The explanation why is in my [1st post](https://github.com/davidstutz/cmsimple-bbclone/issues/6#issue-298086609).
