### ISSUE TITLE
Problem details stats

### ISSUE THREAD

**Issue by truefriend-cz** [davidstutz/cmsimple-bbclone#7]
I have this problem: https://www.phpbb.de/community/viewtopic.php?t=233209#p1332608
Generated empty array in last.php

**Comment by davidstutz** [comment]
I can't really follow what the exact problem is as the threat describes a problem in combination with phpBB, please provide some more details if you need help.

**Comment by truefriend-cz** [comment]
I don't understand what details you want when everything is explained in detail on that link, including the source code (in German). Did you read the texts in German? What parts do you not understand?

**Comment by davidstutz** [comment]
Well, the problem mentioned in the threat deals with an extension for phpBB, not CMSimple. So for me it is unclear what exactly is your problem with the plugin and CMSimple. Also, the code in the threat does not necessarily apply to the CMSImple plugin.

So, for example, what variant and version of CMSimple you are using, what other plugins are you using, what exact error message you get (do you get EXACTLY the same error message as in the threat)?

**Comment by truefriend-cz** [comment]
I have problem with bbclone, no with CMSimple
In your scripts you have contain this scripts of bbclone.

**Comment by davidstutz** [comment]
Yes, but the includes/scripts for BBClone seem to be working. The plugin itself does not change anything in the BBClone code.

**Comment by LukasKysela** [comment]
There's something wrong with that bbclone script. Do you think you could fix this thing in BBClone? The developer is no longer working on the project.

**Comment by davidstutz** [comment]
No likely not, as I am also not actively working on this plugin anymore.
